/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace playlist {
  export interface PlaylistService {
    play(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    pause(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    addSong(
      data: AddSongRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    addSongs(
      data: AddSongsRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    next(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    prev(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    getAllSongs(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<SongsResponse>;
    getSongById(
      data: IdRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<SongResponse>;
    updateSong(
      data: UpdateSongRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    deleteSong(
      data: IdRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
    clear(
      data: google.protobuf.Empty,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<PlaylistResponse>;
  }
  export interface IdRequest {
    id?: number;
  }
  export interface AddSongsRequest {
    songs?: playlist.AddSongRequest[];
  }
  export interface AddSongRequest {
    title?: string;
    duration?: number;
  }
  export interface UpdateSongRequest {
    id?: number;
    newSong?: playlist.AddSongRequest;
  }
  export interface SongsResponse {
    songs?: playlist.SongResponse[];
  }
  export interface SongResponse {
    id?: number;
    title?: string;
    duration?: number;
  }
  export interface PlaylistResponse {
    status?: string;
  }
}
export namespace google {
  export namespace protobuf {
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {}
  }
}
