version: "3.8"

networks:
  playlist-network:
    external: false

services:

  playlist-svc:
    build:
      context: "."
    networks:
      - "playlist-network"
    ports:
      - 50051:${GRPC_PORT}
    depends_on:
      - "db"
    environment:
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:${GRPC_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  db:
    image: "postgres:15.2-alpine"
    networks:
      - "playlist-network"
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

  adminer:
    image: "adminer"
    networks:
      - "playlist-network"
    restart: "on-failure"
    depends_on:
      - "db"
    ports:
      - "8080:8080"