version: "3.8"

networks:
  playlist-network:
    external: false

services:

  playlist-svc:
    build:
      context: "."
    networks:
      - "playlist-network"
    ports:
      - "50051:50051"
    depends_on:
      - "db"
    environment:
      NODE_ENV: "test"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  db:
    image: "postgres:15.2-alpine"
    networks:
      - "playlist-network"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "playlist"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

  adminer:
    image: "adminer"
    networks:
      - "playlist-network"
    restart: "on-failure"
    depends_on:
      - "db"
    ports:
      - "8080:8080"